# -*- coding: utf-8 -*-
"""tts 4 alpro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xv1qy5f7e16knW3xZB_jrgdDxy6ldQCd
"""

# SISTEM PENGELOLAAN HASIL PANEN

data_panen = []


def tambah_panen():
    print("\n=== TAMBAH DATA PANEN ===")

    nama = input("Nama komoditas: ")
    jumlah = float(input("Jumlah panen (kg): "))
    harga = float(input("Harga jual per kg: "))

    data = {
        "nama": nama,
        "jumlah": jumlah,
        "harga": harga
    }

    data_panen.append(data)

    print("Data panen berhasil ditambahkan!")


def tampilkan_panen():
    print("\n=== DATA HASIL PANEN ===")

    if len(data_panen) == 0:
        print("Belum ada data panen.")
    else:
        for i, data in enumerate(data_panen, start=1):
            total = data["jumlah"] * data["harga"]

            print(f"\nData ke-{i}")
            print("Komoditas :", data["nama"])
            print("Jumlah    :", data["jumlah"], "kg")
            print("Harga/kg  : Rp", data["harga"])
            print("Nilai     : Rp", total)


def hitung_total():
    total_berat = 0
    total_nilai = 0

    for data in data_panen:
        total_berat += data["jumlah"]
        total_nilai += data["jumlah"] * data["harga"]

    print("\n=== TOTAL HASIL PANEN ===")
    print("Total berat panen : ", total_berat, "kg")
    print("Total nilai panen : Rp", total_nilai)


def main():
    while True:
        print("\n==============================")
        print("   SISTEM PENGELOLAAN PANEN")
        print("==============================")
        print("1. Tambah data panen")
        print("2. Tampilkan data panen")
        print("3. Hitung total panen")
        print("4. Keluar")

        pilihan = input("Pilih menu: ")

        if pilihan == "1":
            tambah_panen()

        elif pilihan == "2":
            tampilkan_panen()

        elif pilihan == "3":
            hitung_total()

        elif pilihan == "4":
            print("Program selesai. Terima kasih!")
            break

        else:
            print("Pilihan tidak tersedia.")


main()